### ISSUE TITLE
Add line numbers to code snippets, possibly add scrolling

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework.github.io#3]
The google-prettify framework can display line numbers [1], but the formatting of those line numbers is quite ugly. The prettifier uses quite a lot of indirections, why hiding the dot after each line number is not possible using the "standard" way [2].

Another problem of the current code boxes is that they break overlength-lines instead of allowing vertical scrolling.

A good example for code boxes is Gist: https://gist.github.com/Neverlord/a5efdca15300adc421db#file-main-cpp

And here is an example for vertical scrolling: https://gist.github.com/Neverlord/aaf212e49e3ed7ff46ab#file-gistfile1-txt

Switching from google-prettify to something else is also a possibility.

I worked around these problems in the past by embedding Gists [3], but that's not a good solution in the long run, especially for tutorial-like articles.

[1] http://stackoverflow.com/questions/8399547/how-to-add-line-numbers-to-all-lines-in-google-prettify
[2] http://stackoverflow.com/questions/4996904/how-do-you-hide-the-dot-after-the-bullet-number-in-an-ordered-list
[3] http://blog.actor-framework.org/2015-03/version-0-13-released/

**Comment by mavam** [comment]
Does anything speak against using a custom highlighter? For example, I use Pygments to [post-process](https://github.com/mavam/www/blob/master/lib/code.rb) the code blocks placed in `<pre><code>`. Pygments mainly because I contributed a Bro lexer a while ago, and at the time, GitHub used it as their backend. But there exist tons of similar libraries that might directly work with Jekyll.

**Comment by Neverlord** [comment]
Hm, [this SO thread](http://stackoverflow.com/questions/11093241/how-to-support-line-number-when-using-pygments-with-jekyll) popped up on a quick web search. Is there any way to generate the code highlighting from Markdown blocks? This `{% highlight ... %}` syntax is quite ugly. Wouldn't be a deal-breaker, though.

Can you set this up in a branch?

**Comment by mavam** [comment]
>  This `{% highlight ... %}` syntax is quite ugly.

Really not pretty. I use nanoc and kramdown for my personal blog. Seems like kramdown comes with [the features you want](http://kramdown.gettalong.org/quickref.html#code-blocks) and Jekyll also supports it. Plain kramdown uses coderay for the highlighting, but I use Pygments for reasons stated above. For parsing, kramdown also supports Github-flavored Markdown (e.g., the ```lang syntax).

> Can you set this up in a branch?

I wish I had the cycles, but I'm bogged down until the end of September.
